### ISSUE TITLE
InvalidOperationException when using IEnumerable child property.

### ISSUE THREAD

**Issue by davidjamesb** [nathan-parkinson/linq2db.include#5]
When using a simple one-to-many association as follows:

```
[Association(ThisKey = nameof(Id), OtherKey = nameof(Child.ParentId))]
public List<Child> Children { get; set; } = new List<Child>();
```

All is well. Changing this to IEnumerable causes a **System.InvalidOperationException: 'This operation is only valid on generic types.**

```
[Association(ThisKey = nameof(Id), OtherKey = nameof(Child.ParentId))]
public IEnumerable<Child> Children { get; set; } = new List<Child>();
```
**IList** and **ICollection** also work correctly, so I assume the problem is co-variance of **IEnumerable**.

**Comment by nathan-parkinson** [comment]
IEnumerable<> lacks an Add method which is, of course, required by Linq2db.include to add objects to the enumerable.  

ASAIK other similar frameworks (EF core) also do not work with IEnumerables.  

I did, at some point, add code to check if the IEnumerable<> property was null.  If it is then the code would create a list, work with that and then set it to the IEnumerable<> property when done.  But this did not work with properties that were not null as there were too many possibilities of what the instantiated object could be.  It could be a list, dictionary, an immutable lookup etc.  Or even a developers custom implementation that may or may not have parameterless constructor.  

Without the ability to guarantee that the library would\could create the correct type it would be a negative thing to replace a object instantiated by the developer with an object of a different type.  This could change behavior significantly.   

So, on balance, I decided not to set values on instantiated IEnumerable<> properties.   

I'm not sure if the code to create it as a list if the value is null is still in the library or not.  You can test that out easily by removing the default `= new List<Child>();` and see if it works, or wait till i can confirm this outside of my office hours.  

I'm not dead set on this logic though.  If there is a way to correctly use whatever type the property is instantiated as then I would use it, I just don't see a way to do this.

Hope this helps

**Comment by davidjamesb** [comment]
Removing the default `= new List<Child>();` also works correctly when not using an IEnumerable property. Entity framework supports IEnumerable navigation properties as does Linq2DB when used with LoadWith() - in fact the default T4 Linq2DB templates generate associations using IEnumerable properties.

However, I appreciate the response although I would add that perhaps a better exception message is needed if you are to keep this behaviour as we were left scratching our heads to what **This operation is only valid on generic types** meant when we were in fact using `IEnumerable<T>`.

**Comment by nathan-parkinson** [comment]
You make a good point

I just created a test to prove\disprove what I just said and you are right.  The IEnumerable<> properties work fine in EF Core.  I remember creating test for this in the past but remember the result differently. Perhaps it was flawed, or my memory sucks.  

Anyway, I'll see what I can do to get IEnumerable<> properties working.  

Also, good point about the confusing errors.  I will try to address this too, if it's still relevant after the other changes.

**Comment by nathan-parkinson** [comment]
@DJBMASTER 

The issue should be resolved now.  `IEnumerable<>` will be cast to `IConnection<>` if they are not null.  

Properties with null values will be created in the following way:
* `IEnumerable<T>` as `Collection<T>`
* `ICollection<T>` as `Collection<T>`
* `ISet<T>` as `HashSet<T>`
* `IList<T>` as `List<T>`

Thanks for reporting the issue.
